region: ap-northeast-1
cluster: my-cluster

params:
  ImageTag: latest
  # LogGroup:
  ExecutionRoleArn: my-task-execution-role-arn
  TaskRoleArn: my-task-role-arn
  ApiTargetGroupArn: my-alb-target-group-arn

task_definitions:
  - name: API
    base_file: common_td.json
    file: api_td.json
  - name: Worker
    base_file: common_td.json
    file: worker_td.json
services:
  - name: API
    task_definition: API
    file: api_service.json
  - name: Worker
    task_definition: Worker
    file: worker_service.json
