region: ap-northeast-1
cluster: my-cluster

params:
  ImageTag: latest
  # LogGroup:
  ExecutionRoleArn: my-task-execution-role-arn
  TaskRoleArn: my-task-role-arn
  ApiTargetGroupArn: my-alb-target-group-arn

task_definitions:
  - name: api
    base_file: common_td.json
    file: api_td.json
  - name: worker
    base_file: common_td.json
    file: worker_td.json
services:
  - name: test-api
    task_definition: api
    file: api_service.json
  - name: test-worker
    task_definition: worker
    file: worker_service.json
